apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-lms-storage-pv
  namespace: teamtwo-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/data
  storageClassName: manual
