apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lms-app
  namespace: teamtwo-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-app
  template:
    metadata:
      labels:
        app: lms-app
    spec:
      containers:
      - name: lms-app
        image: xbahrawy/finalproject:latest
        ports:
        - containerPort: 5000
